---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/neieva04/public_html/
    - /usr/bin/rsync -a --no-perms --exclude='.git' --exclude='.github' --exclude='.vercel' --exclude='.claude' --exclude='.gitignore' --exclude='.cpanel.yml' --exclude='site.zip' --exclude='site1.2.zip' ./ "$DEPLOYPATH"
